### PR TITLE
Implement Transit gateway metrics and ec2 exporter

### PR DESCRIPTION
**Pull request by mrWinston**
This PR adds the following two metrics:
```
ec2_transitgateways_quota
ec2_transitgateways_usage
```
As well as a new ec2 exporter. The configuration of the EC2 Exporter is exactly the same as with the VPC Exporter.

### CODE REVIEW

**Comment by maorfr** [comment]
when adding a new module, the configuration should be updated in advance.
for example: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/45138

**Comment by maorfr** [comment]
is there a way to test it?

**Review by maorfr — APPROVED** [review]
i believe you are missing a log statement ("will metrics be gathered?")

**Comment by mrWinston** [comment]
@maorfr I've added the log statement and updated the README. Additionally, i've renamed the metric in question slightly.

**Pull request merged**
