### PR TITLE
Fix nil pointer references

### PR DESCRIPTION
**Pull request by janboll**
The vpc.go sometimes crashes with nil pointer reference. The stacktrace indicates, that it's related to nil values returned for certain AWS calls

### CODE REVIEW

**Review by mrWinston — APPROVED** [review]
/lgtm

I'm wondering if we should provide a more precise error message in the logs in case that error happens. But its not a blocker for me as we can find out if it happened by searching for error logs that have "err=nil".

**Comment by patjlm** [comment]
For my knowledge, in which case do we get `nil` there, without any error ?

**Comment by janboll** [comment]
That's a very good question. I was fingering from the fact, that the function returns a pointer. Also the code is failing at i.e. line 154, if you check that line the only thing, that can be nil is the output.  Not sure, but it might be an issue with the SDK, found for instance: https://github.com/aws/aws-sdk-go/issues/3619
I'll go ahead and upgrade the SDK to the latest 1.x release.

**Comment by janboll** [comment]
Tested locally using our stage and prod AWS accounts.

**Comment by janboll** [comment]
Removed the nil check and just bumped the SDK to check if was only an upstream issue.

**Review by patjlm — APPROVED** [review]
LGTM

**Pull request merged**
